#!/usr/bin/env python 
# -*- coding: utf-8 -*- 


try:
    import chomikdownloader.main
    chomikdownloader.main.start()
    #raise ImportError
except ImportError, e:
    import src.main
    src.main.start()
